version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: Jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Amsterdam
       ports:
            - 5056:5055
       volumes:
            - /volume2/docker/jellyseerr:/app/config:rw
       restart: unless-stopped