version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Amsterdam
       ports:
            - 5055:5055
       volumes:
            - /volume1/docker/jellyseerr:/app/config:rw
       restart: unless-stopped