# Create folder homarr > data and icons

version: "3.9"
services:
  homarr:
    container_name: Homarr
    image: ghcr.io/ajnart/homarr:latest
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 4755:7575
    volumes:
      - /volume1/docker/homarr:/app/data/configs:rw
      - /volume1/docker/homarr/data:/data:rw
      - /volume1/docker/homarr/icons:/app/public/icons:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
     TZ: Europe/Amsterdam