## ## Create folder sabnzbd > config, downloads and incomplete-downloads.

version: '3.9'
services:
 sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: SABnzbd
    healthcheck:
     test: curl -f http://localhost:8080/ || exit 1
    restart: on-failure:5
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume2/docker/sabnzbd/config:/config:rw
      - /volume1/Media/Downloads:/downloads:rw 
      - /volume1/Media/Temp:/incomplete-downloads:rw 
    environment:
      TZ: Europe/Amsterdam
      PGID: 100
      PUID: 1026
    ports:
      - 8775:8080
      - 9093:9090