## Create folder Radarr > Config

version: '3.9'
services:
 radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    healthcheck:
     test: curl -f http://localhost:7878/ || exit 1
    restart: on-failure:5
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume2/docker/radarr/config:/config:rw 
      - /volume1/Media:/media:rw 
    environment:
      TZ: Europe/Bucharest
      PGID: 100
      PUID: 1026
    ports:
      - 7878:7878
